spring:
    profiles:
        active: ${SPRING_PROFILES_ACTIVE}

application:
    title: api-rest-demo
    description: api-rest-demo to learn how to create a REST API with Spring Boot
    version: 1.0.0
